---
### DEFAULT VARIABLES: Only modify if you know what you are doing
# Important Note: The playbook_dir is the root of the project repo
directory:
  # Standard directories
  ansible:    "{{ playbook_dir }}/"
  packer:     "{{ playbook_dir }}/../packer/"
  terraform:  "{{ playbook_dir }}/../terraform/"
  # Configuration directories 
  ansible_config:   "{{ playbook_dir }}/group_vars/"
  packer_config:    "{{ playbook_dir }}/template/config_packer/"
  terraform_config: "{{ playbook_dir }}/template/config_terraform/"

configuration:
  default:
    varfile: "{{ directory.ansible_config }}/default.yml"
  master:
    varfile: "{{ directory.ansible_config }}/master.yml"
  on_runtime:
    varfile: "{{ directory.ansible_config }}/on_runtime.yml"

  terraform:
    master:
      varfile: "{{ directory.terraform_config }}/minecraftAWS.tfvars"

  packer:
    jenkins:
      varfile: "{{ directory.packer_config }}/jenkins/jenkins.pkrvars.hcl"
      nginxconfig_jenkins_yml: "{{ directory.packer_config }}/jenkins/nginxconfig_jenkins.yml"

output:
  packer:
    jenkins: "{{ directory.packer }}/jenkins_manifest.json"

