---
gitrepo:
  nginx: "https://github.com/thehenrylam/SimpleNginx.git"
  jenkins: "https://github.com/thehenrylam/SimpleJenkins.git"

jenkins:
  cert:
    country_name: "US"
    state_name: "CA"
    local_name: "San Francisco"
    org_name: "Example Corp"
    unit_name: "Example Corp"
    common_name: "Example"
    email_address: ""
