---
- name: Check if repo folder exists
  stat: 
    path: "{{ host_dir }}/jenkins/"
  register: repo_folder

- name: Make sure that the jenkins environment is turned off
  command: docker compose down
  args:
    chdir: "{{ host_dir }}/jenkins/"
  when: repo_folder.stat.exists

