---
- name: Check if repo folder exists
  stat: 
    path: "{{ host_dir }}/jenkins/"
  register: repo_folder

- name: Make sure that the jenkins environment is turned on
  command: docker compose up --build -d
  args:
    chdir: "{{ host_dir }}/jenkins/"
  when: repo_folder.stat.exists

