---
- name: Load default variables
  include_vars: "{{ role_path }}/../../group_vars/default.yml"

- name: Gather All Facts
  set_fact: 
    # This is done so that the role will stop earlier if aws_profile was not provided
    aws_profile: "{{ aws_profile }}" 
    # Get the target directory (placed at the end for easy modification)
    target_dir: "{{ directory.terraform }}/foundation/"

- name: Initialize Terraform Module
  ansible.builtin.shell: "tofu init"
  args:
    chdir: "{{ target_dir }}"

# -auto-approve is omitted because tofu plan shouldn't need any approval
- name: Plan Terraform Module
  ansible.builtin.shell: >
    TF_LOG=info 
    AWS_PROFILE="{{ aws_profile }}" 
    tofu plan 
    -var-file="{{ configuration.terraform_varfile }}" 
    -compact-warnings
  args:
    chdir: "{{ target_dir }}"

