---
### Ensure that the terraform variable file is up-to-date
- name: Update Terraform Variable file is up-to-date
  template:
    src: "{{ configuration.terraform.master.varfile }}.j2"
    dest: "{{ configuration.terraform.master.varfile }}"

# Plan Terraform Module
- name: Plan Terraform Module
  include_role: 
    name: utility-terraform-execute
  vars:
    aws_profile: "{{ aws_profile }}"
    command: "plan"
    varfile: "{{ configuration.terraform.master.varfile }}"
    target_dir: "{{ directory.terraform }}/foundation/"
